#!/bin/sh

set -e

case "$1" in
    configure)
	update-alternatives --install /usr/local/bin/mpv mpv /usr/bin/umpv 100
	;;

    abort-upgrade|abort-deconfigure|abort-remove)
	;;

    *)
	echo "$0 called with unknown argument \`$1'" 1>&2
	exit 1
	;;
esac

#DEBHELPER#
exit 0